package(default_visibility = [
        '//tools/toolchain/v3:__pkg__',
        ])

filegroup(
  name = 'ar',
  srcs = [
    '@toolchain_potato_archive//:ar',
    'potato-ar',
  ],
)

filegroup(
  name = 'as',
  srcs = [
    '@toolchain_potato_archive//:as',
    'potato-as',
  ],
)

filegroup(
  name = 'cpp',
  srcs = [
    '@toolchain_potato_archive//:cpp',
    'potato-cpp',
  ],
)

filegroup(
  name = 'gcc',
  srcs = [
    '@toolchain_potato_archive//:gcc',
    '@toolchain_potato_archive//:g++',
    'potato-gcc',
  ],
)

filegroup(
  name = 'g++',
  srcs = [
    '@toolchain_potato_archive//:g++',
    'potato-g++',
  ],
)

filegroup(
  name = 'gcov',
  srcs = [
    '@toolchain_potato_archive//:gcov',
    'potato-gcov',
  ],
)

filegroup(
  name = 'ld',
  srcs = [
    '@toolchain_potato_archive//:ld',
    'potato-ld',
  ],
)

filegroup(
  name = 'objcopy',
  srcs = [
    '@toolchain_potato_archive//:objcopy',
    'potato-objcopy',
  ],
)

filegroup(
  name = 'objdump',
  srcs = [
    '@toolchain_potato_archive//:objdump',
    'potato-objdump',
  ],
)

filegroup(
  name = 'strip',
  srcs = [
    '@toolchain_potato_archive//:strip',
    'potato-strip',
  ],
)

filegroup(
    name = 'compiler_pieces',
    srcs = [
    '@toolchain_potato_archive//:compiler_pieces',
    ],
)
