package(default_visibility = [
        '//tools/toolchain:__pkg__',
        '//tools/toolchain/v3-gpu:__pkg__',
        ])

filegroup(
  name = 'ar',
  srcs = [
    '@toolchain_v3_archive//:ar',
    'v3-ar',
  ],
)

filegroup(
  name = 'as',
  srcs = [
    '@toolchain_v3_archive//:as',
    'v3-as',
  ],
)

filegroup(
  name = 'cpp',
  srcs = [
    '@toolchain_v3_archive//:cpp',
    'v3-cpp',
  ],
)

filegroup(
  name = 'gcc',
  srcs = [
    '@toolchain_v3_archive//:gcc',
    'v3-gcc',
  ],
)

filegroup(
  name = 'g++',
  srcs = [
    '@toolchain_v3_archive//:g++',
    'v3-g++',
  ],
)

filegroup(
  name = 'gcov',
  srcs = [
    '@toolchain_v3_archive//:gcov',
    'v3-gcov',
  ],
)

filegroup(
  name = 'ld',
  srcs = [
    '@toolchain_v3_archive//:ld',
    'v3-ld',
  ],
)

filegroup(
  name = 'objcopy',
  srcs = [
    '@toolchain_v3_archive//:objcopy',
    'v3-objcopy',
  ],
)

filegroup(
  name = 'objdump',
  srcs = [
    '@toolchain_v3_archive//:objdump',
    'v3-objdump',
  ],
)

filegroup(
  name = 'strip',
  srcs = [
    '@toolchain_v3_archive//:strip',
    'v3-strip',
  ],
)

filegroup(
    name = 'compiler_pieces',
    srcs = [
    '@toolchain_v3_archive//:compiler_pieces',
    ],
)
