# gas-preprocessor.pl: upstream is at https://github.com/libav/gas-preprocessor
# Modified by adding a pseudo-section __LLVM,__asm.

filegroup(
    name = "gas-preprocessor",
    srcs = [
        "gas-preprocessor.pl",
        ],
    visibility = [
        "//visibility:public",
        ],
    )
