#!/usr/bin/env python
import sys
sys.path.append('tools/toolchain/nvcc_wrapper')
import nvcc_wrapper

if __name__ == '__main__':
  nvcc_wrapper.CPU_COMPILER = ('external/toolchain_v3_tk1_archive/usr/bin/armv7a-hardfloat-linux-gnueabi-gcc')
  nvcc_wrapper.GCC_HOST_COMPILER_PATH = ('external/toolchain_v3_tk1_archive/usr/bin/armv7a-hardfloat-linux-gnueabi-gcc')
  nvcc_wrapper.NVCC_PATH = 'external/cuda_6_5_archive/bin/nvcc --target-cpu-architecture ARM -m32'
  nvcc_wrapper.SUPPORTED_CUDA_COMPUTE_CAPABILITIES = [ "3.2" ]

  sys.exit(nvcc_wrapper.main())
