package(default_visibility = [
        '//tools/toolchain/v3:__pkg__',
        '//tools/toolchain/v3/v3-tx1-gpu:__pkg__',
        ])

filegroup(
  name = 'ar',
  srcs = [
    '@toolchain_v3_tx1_archive//:ar',
    'v3-tx1-ar',
  ],
)

filegroup(
  name = 'as',
  srcs = [
    '@toolchain_v3_tx1_archive//:as',
    'v3-tx1-as',
  ],
)

filegroup(
  name = 'cpp',
  srcs = [
    '@toolchain_v3_tx1_archive//:cpp',
    'v3-tx1-cpp',
  ],
)

filegroup(
  name = 'gcc',
  srcs = [
    '@toolchain_v3_tx1_archive//:gcc',
    'v3-tx1-gcc',
  ],
)

filegroup(
  name = 'g++',
  srcs = [
    '@toolchain_v3_tx1_archive//:g++',
    'v3-tx1-g++',
  ],
)

filegroup(
  name = 'gcov',
  srcs = [
    '@toolchain_v3_tx1_archive//:gcov',
    'v3-tx1-gcov',
  ],
)

filegroup(
  name = 'ld',
  srcs = [
    '@toolchain_v3_tx1_archive//:ld',
    'v3-tx1-ld',
  ],
)

filegroup(
  name = 'objcopy',
  srcs = [
    '@toolchain_v3_tx1_archive//:objcopy',
    'v3-tx1-objcopy',
  ],
)

filegroup(
  name = 'objdump',
  srcs = [
    '@toolchain_v3_tx1_archive//:objdump',
    'v3-tx1-objdump',
  ],
)

filegroup(
  name = 'strip',
  srcs = [
    '@toolchain_v3_tx1_archive//:strip',
    'v3-tx1-strip',
  ],
)

filegroup(
    name = 'compiler_pieces',
    srcs = [
    '@toolchain_v3_tx1_archive//:compiler_pieces',
    ],
)
