package(default_visibility = [
        '//tools/toolchain/v3:__pkg__',
        ])

filegroup(
  name = 'ar',
  srcs = [
    '@toolchain_v3_tk1_gcc5_archive//:ar',
    'v3-tk1-ar',
  ],
)

filegroup(
  name = 'as',
  srcs = [
    '@toolchain_v3_tk1_gcc5_archive//:as',
    'v3-tk1-as',
  ],
)

filegroup(
  name = 'cpp',
  srcs = [
    '@toolchain_v3_tk1_gcc5_archive//:cpp',
    'v3-tk1-cpp',
  ],
)

filegroup(
  name = 'gcc',
  srcs = [
    '@toolchain_v3_tk1_gcc5_archive//:gcc',
    'v3-tk1-gcc',
  ],
)

filegroup(
  name = 'g++',
  srcs = [
    '@toolchain_v3_tk1_gcc5_archive//:g++',
    'v3-tk1-g++',
  ],
)

filegroup(
  name = 'gcov',
  srcs = [
    '@toolchain_v3_tk1_gcc5_archive//:gcov',
    'v3-tk1-gcov',
  ],
)

filegroup(
  name = 'ld',
  srcs = [
    '@toolchain_v3_tk1_gcc5_archive//:ld',
    'v3-tk1-ld',
  ],
)

filegroup(
  name = 'objcopy',
  srcs = [
    '@toolchain_v3_tk1_gcc5_archive//:objcopy',
    'v3-tk1-objcopy',
  ],
)

filegroup(
  name = 'objdump',
  srcs = [
    '@toolchain_v3_tk1_gcc5_archive//:objdump',
    'v3-tk1-objdump',
  ],
)

filegroup(
  name = 'strip',
  srcs = [
    '@toolchain_v3_tk1_gcc5_archive//:strip',
    'v3-tk1-strip',
  ],
)

filegroup(
    name = 'compiler_pieces',
    srcs = [
    '@toolchain_v3_tk1_gcc5_archive//:compiler_pieces',
    ],
)
