#!/usr/bin/env python
import sys
sys.path.append('tools/toolchain/nvcc_wrapper')
import nvcc_wrapper

if __name__ == '__main__':
  nvcc_wrapper.CPU_COMPILER = ('external/toolchain_v3_tx1_archive/usr/bin/aarch64-tx1-linux-gnu-gcc')
  nvcc_wrapper.GCC_HOST_COMPILER_PATH = ('external/toolchain_v3_tx1_archive/usr/bin/aarch64-tx1-linux-gnu-gcc')
  nvcc_wrapper.NVCC_PATH = 'external/cuda_7_0_archive/bin/nvcc'
  nvcc_wrapper.SUPPORTED_CUDA_COMPUTE_CAPABILITIES = [ "5.3" ]

  sys.exit(nvcc_wrapper.main())
