#!/usr/bin/env python
import sys
sys.path.append('tools/toolchain/nvcc_wrapper')
import nvcc_wrapper

if __name__ == '__main__':
  nvcc_wrapper.CPU_COMPILER = ('external/toolchain_v3_archive/usr/bin/x86_64-megvii-linux-gnu-gcc')
  nvcc_wrapper.GCC_HOST_COMPILER_PATH = ('external/toolchain_v3_archive/usr/bin/x86_64-megvii-linux-gnu-gcc')
  nvcc_wrapper.NVCC_PATH = 'external/cuda_7_5_archive/bin/nvcc'
  nvcc_wrapper.SUPPORTED_CUDA_COMPUTE_CAPABILITIES = [ "3.5", "5.0", "5.2" ]

  sys.exit(nvcc_wrapper.main())
