package(default_visibility = [
        '//tools/toolchain/v3:__pkg__',
        ])

filegroup(
  name = 'ar',
  srcs = [
    '@android_ndk_r14b_piii_archive//:ar',
    'ndk-ar',
  ],
)

filegroup(
  name = 'as',
  srcs = [
    '@android_ndk_r14b_piii_archive//:as',
    'ndk-as',
  ],
)

filegroup(
  name = 'cpp',
  srcs = [
    '@android_ndk_r14b_piii_archive//:cpp',
    'ndk-cpp',
  ],
)

filegroup(
  name = 'gcc',
  srcs = [
    '@android_ndk_r14b_piii_archive//:gcc',
    'ndk-gcc',
  ],
)

filegroup(
  name = 'g++',
  srcs = [
    '@android_ndk_r14b_piii_archive//:g++',
    'ndk-g++',
  ],
)

filegroup(
  name = 'gcov',
  srcs = [
    '@android_ndk_r14b_piii_archive//:gcov',
    'ndk-gcov',
  ],
)

filegroup(
  name = 'ld',
  srcs = [
    '@android_ndk_r14b_piii_archive//:ld',
    'ndk-ld',
  ],
)

filegroup(
  name = 'objcopy',
  srcs = [
    '@android_ndk_r14b_piii_archive//:objcopy',
    'ndk-objcopy',
  ],
)

filegroup(
  name = 'objdump',
  srcs = [
    '@android_ndk_r14b_piii_archive//:objdump',
    'ndk-objdump',
  ],
)

filegroup(
  name = 'strip',
  srcs = [
    '@android_ndk_r14b_piii_archive//:strip',
    'ndk-strip',
  ],
)

filegroup(
    name = 'compiler_pieces',
    srcs = [
    '@android_ndk_r14b_piii_archive//:compiler_pieces',
    ],
)
