package(default_visibility = [
        '//tools/toolchain/v3:__subpackages__',
        ])

filegroup(
  name = 'ar',
  srcs = [
    'v3-link.py',
  ],
)

filegroup(
  name = 'as',
  srcs = [
    'v3-nop',
  ],
)

filegroup(
  name = 'cpp',
  srcs = [
    'v3-cl.py',
  ],
)

filegroup(
  name = 'gcc',
  srcs = [
    'v3-cl.py',
  ],
)

filegroup(
  name = 'g++',
  srcs = [
    'v3-cl.py',
  ],
)

filegroup(
  name = 'gcov',
  srcs = [
    'v3-nop',
  ],
)

filegroup(
  name = 'ld',
  srcs = [
    'v3-link.py',
  ],
)

filegroup(
  name = 'objcopy',
  srcs = [
    'v3-nop',
  ],
)

filegroup(
  name = 'objdump',
  srcs = [
    'v3-nop',
  ],
)

filegroup(
  name = 'strip',
  srcs = [
    'v3-strip.py',
  ],
)

filegroup(
    name = 'compiler_pieces',
    srcs = [
      'common.py',
      'makesln.py',
    ],
)
