package(default_visibility = [
        '//visibility:public',
        ])

############### Toolchains
config_setting (
    name = "linux_x86_64_gcc4",
    values = {
        "cpu": "k8_gcc4",
        "compiler": "gcc",
    },
)

config_setting (
    name = "linux_x86_64_gcc4_cuda7",
    values = {
        "cpu": "k8_gcc4",
        "compiler": "gcc_cuda",
    },
)

config_setting (
    name = "linux_x86_64_gcc4_cuda8",
    values = {
        "cpu": "k8_gcc4_cuda8",
        "compiler": "gcc_cuda",
    },
)

config_setting (
    name = "linux_x86_64_gcc5",
    values = {
        "cpu": "k8",
        "compiler": "gcc",
    },
)

config_setting (
    name = "linux_x86_64_gcc5_cuda8",
    values = {
        "cpu": "k8",
        "compiler": "gcc_cuda",
    },
)

config_setting (
    name = "linux_x86_32",
    values = {
        "cpu": "piii",
    },
)

config_setting (
    name = "windows_x86_64_xclang",
    values = {
        "cpu": "windows_x86_64",
        "compiler": "xclang",
   },
)

config_setting (
    name = "windows_x86_32_xclang",
    values = {
        "cpu": "windows_x86_32",
        "compiler": "xclang",
   },
)

config_setting (
    name = "windows_x86_64_xclang_cuda8",
    values = {
        "cpu": "windows_x86_64_cuda",
        "compiler": "xclang_cuda",
   },
)

config_setting (
    name = "tk1_gcc",
    values = {
        "cpu": "tk1",
        "compiler": "gcc",
    },
)

config_setting (
    name = "tk1_gcc_cuda",
    values = {
        "cpu": "tk1",
        "compiler": "gcc_cuda",
    },
)

config_setting (
    name = "c3s_gcc",
    values = {
        "cpu": "c3s",
        "compiler": "gcc",
    },
)

config_setting (
    name = "potato_gcc",
    values = {
        "cpu": "potato",
        "compiler": "gcc",
    },
)
config_setting (
    name = "tx1_gcc",
    values = {
        "cpu": "tx1",
        "compiler": "gcc",
    },
)

config_setting (
    name = "tx1_gcc_cuda",
    values = {
        "cpu": "tx1",
        "compiler": "gcc_cuda",
    },
)

config_setting (
    name = "android_armv7",
    values = {
        "cpu": "android_armv7",
    },
)

config_setting (
    name = "android_aarch64",
    values = {
        "cpu": "android_aarch64",
    },
)

config_setting (
    name = "android_x86_32",
    values = {
        "cpu": "android_piii",
    },
)

config_setting (
    name = "android_x86_32_sse3",
    values = {
        "cpu": "android_piii_sse3",
    },
)

config_setting (
    name = "ios_armv7",
    values = {
        "cpu": "ios_armv7",
    },
)

config_setting (
    name = "ios_armv7s",
    values = {
        "cpu": "ios_armv7s",
    },
)

config_setting (
    name = "ios_aarch64",
    values = {
        "cpu": "ios_aarch64",
    },
)

############### Toolchain Groups: CPU
config_setting (
    name = "cpu_tk1",
    values = {
        "cpu": "tk1",
    },
)

config_setting (
    name = "cpu_c3s",
    values = {
        "cpu": "c3s",
    },
)

config_setting (
    name = "cpu_potato",
    values = {
        "cpu": "potato",
    },
)

config_setting (
    name = "cpu_tx1",
    values = {
        "cpu": "tx1",
    },
)

config_setting (
    name = "cpu_windows_x86_32",
    values = {
        "cpu": "windows_x86_32",
    },
)

config_setting (
    name = "cpu_windows_x86_64",
    values = {
        "cpu": "windows_x86_64",
    },
)

config_setting (
    name = "cpu_windows_x86_64_cuda",
    values = {
        "cpu": "windows_x86_64_cuda",
    },
)

config_setting (
    name = "cpu_linux_x86_64",
    values = {
        "cpu": "k8",
    },
)

config_setting (
    name = "cpu_linux_x86_64_gcc4",
    values = {
        "cpu": "k8_gcc4",
    },
)

config_setting (
    name = "cpu_linux_x86_64_gcc4_cuda8",
    values = {
        "cpu": "k8_gcc4_cuda8",
    },
)

############### Toolchain Groups: Compiler
config_setting (
    name = "compiler_gcc",
    values = {
        "compiler": "gcc",
    },
)

config_setting (
    name = "compiler_gcc_cuda",
    values = {
        "compiler": "gcc_cuda",
    },
)

config_setting (
    name = "compiler_clang",
    values = {
        "compiler": "clang",
    },
)

config_setting (
    name = "compiler_xclang",
    values = {
        "compiler": "xclang",
    },
)

config_setting (
    name = "compiler_xclang_cuda",
    values = {
        "compiler": "xclang_cuda",
    },
)

############### Optimization options
config_setting (
    name = "fastbuild",
    values = {
        "compilation_mode": "fastbuild",
    },
)

config_setting (
    name = "dbg",
    values = {
        "compilation_mode": "dbg",
    },
)

config_setting (
    name = "opt",
    values = {
        "compilation_mode": "opt",
    },
)
