package(default_visibility = [
        '//visibility:public',
        ])

############### Toolchains
config_setting (
    name = "x86_64_gcc",
    values = {
        "cpu": "k8",
        "compiler": "gcc",
    },
)

config_setting (
    name = "x86_64_gcc_cuda",
    values = {
        "cpu": "k8",
        "compiler": "gcc_cuda",
    },
)

config_setting (
    name = "x86_64_gcc_cuda8",
    values = {
        "cpu": "k8",
        "compiler": "gcc_cuda8",
    },
)

config_setting (
    name = "tk1_gcc",
    values = {
        "cpu": "tk1",
        "compiler": "gcc",
    },
)

config_setting (
    name = "tk1_gcc_cuda",
    values = {
        "cpu": "tk1",
        "compiler": "gcc_cuda",
    },
)

config_setting (
    name = "tx1_gcc",
    values = {
        "cpu": "tx1",
        "compiler": "gcc",
    },
)

config_setting (
    name = "tx1_gcc_cuda",
    values = {
        "cpu": "tx1",
        "compiler": "gcc_cuda",
    },
)

config_setting (
    name = "android_armv7",
    values = {
        "cpu": "android_armv7",
    },
)

config_setting (
    name = "android_aarch64",
    values = {
        "cpu": "android_aarch64",
    },
)

config_setting (
    name = "ios_armv7",
    values = {
        "cpu": "ios_armv7",
    },
)

config_setting (
    name = "ios_aarch64",
    values = {
        "cpu": "ios_aarch64",
    },
)

############### Toolchain Groups
config_setting (
    name = "gcc",
    values = {
        "compiler": "gcc",
    },
)

config_setting (
    name = "tk1",
    values = {
        "cpu": "tk1",
    },
)

config_setting (
    name = "tx1",
    values = {
        "cpu": "tx1",
    },
)

config_setting (
    name = "x86_64",
    values = {
        "cpu": "k8",
    },
)

config_setting (
    name = "gcc_cuda",
    values = {
        "compiler": "gcc_cuda",
    },
)

config_setting (
    name = "gcc_cuda8",
    values = {
        "compiler": "gcc_cuda8",
    },
)

config_setting (
    name = "clang",
    values = {
        "compiler": "clang",
    },
)

############### Optimization options
config_setting (
    name = "fastbuild",
    values = {
        "compilation_mode": "fastbuild",
    },
)

config_setting (
    name = "dbg",
    values = {
        "compilation_mode": "dbg",
    },
)

config_setting (
    name = "opt",
    values = {
        "compilation_mode": "opt",
    },
)
