config_setting (
    name = "tk1",
    values = {
        "cpu": "tk1",
    },
    visibility = ["//visibility:public"],
)

config_setting (
    name = "tx1",
    values = {
        "cpu": "tx1",
    },
    visibility = ["//visibility:public"],
)

config_setting (
    name = "x86_64",
    values = {
        "cpu": "k8",
    },
    visibility = ["//visibility:public"],
)

config_setting (
    name = "gcc_cuda",
    values = {
        "compiler": "gcc_cuda",
    },
    visibility = ["//visibility:public"],
)

config_setting (
    name = "tk1_gcc_cuda",
    values = {
        "cpu": "tk1",
        "compiler": "gcc_cuda",
    },
    visibility = ["//visibility:public"],
)

config_setting (
    name = "tx1_gcc_cuda",
    values = {
        "cpu": "tx1",
        "compiler": "gcc_cuda",
    },
    visibility = ["//visibility:public"],
)

config_setting (
    name = "x86_64_gcc_cuda",
    values = {
        "cpu": "x86_64",
        "compiler": "gcc_cuda",
    },
    visibility = ["//visibility:public"],
)
